// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSW3frfuVQi8L3O3prDus3i3Hgv-zdr4o',
    appId: '1:633814047663:web:6167b225e752e967e3ad5a',
    messagingSenderId: '633814047663',
    projectId: 'breastadvocate-c3436',
    authDomain: 'breastadvocate-c3436.firebaseapp.com',
    storageBucket: 'breastadvocate-c3436.appspot.com',
    measurementId: 'G-H0HL8DZ7P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiO2RngLvzcfBX-bPX_sqG6fvT_1KnfF8',
    appId: '1:633814047663:android:3aa1326daa429f99e3ad5a',
    messagingSenderId: '633814047663',
    projectId: 'breastadvocate-c3436',
    storageBucket: 'breastadvocate-c3436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlbRS4QLEdKXOS80YyR4qw01U098XUtUI',
    appId: '1:633814047663:ios:805677d4a7fed78de3ad5a',
    messagingSenderId: '633814047663',
    projectId: 'breastadvocate-c3436',
    storageBucket: 'breastadvocate-c3436.appspot.com',
    iosBundleId: 'com.example.pinkgirl',
  );
}
